### PR TITLE
Add step to compute and store residualized matrix

### PR DESCRIPTION
**Pull request by kelshmo**
Fixes #103. 

This PR adds a new function `compute_residuals` to calculate residuals from the best model and adjust for signal accordingly in the counts matrix. The signal from the predictor or primary variable is preserved. This PR includes testing and documentation. Please review the test carefully to confirm this code is statistically sound! The counts are adjusted with `variancePartition::dream()` and then matrix mathematics are performed to add back predictor signal. The primary variable is identified in the design matrix using `grep()`.

This PR also broadens the definition of `x_var` in the config. The name of the variable is misleading but I wanted to preserve the variable name as to not break our users existing code. `x_var` is used in the regression model as the baseline model and is also used in `compute_residuals` as the variable's weighted residuals to add back to the matrix.   

With some lengthy and verbose code, the matrix is stored in Synapse. Although, I need to test upload explicitly.

### CODE REVIEW

**Comment by jgockley62** [comment]
@kelshmo Missing a closed parenthesis here: https://github.com/Sage-Bionetworks/sageseqr/blob/f5040c15cf5fbd68a9600fd9607a851461c12fdf/inst/_targets.R#L147

**Comment by kelshmo** [comment]
@jgockley62 fixed the parenthesis!

**Comment by jgockley62** [comment]
@kelshmo `clean_metadata` should be `clean_md` https://github.com/Sage-Bionetworks/sageseqr/blob/f5040c15cf5fbd68a9600fd9607a851461c12fdf/R/functions.R#L970

**Comment by jgockley62** [comment]
The same issue as `de` exists:
```
Total:275 s
Error in variancePartition::dream(exprObj = voom, formula = metadata_input$formula,  : 
  exprObj and weightsMatrix must be the same dimensions
In addition: There were 50 or more warnings (use warnings() to see the first 50)
```
Would the easiest fix be to filter out the zero'd genes in `cqn_counts` document the gene names for the report and return a new `filtered_counts` object?

**Pull request merged**
